### ISSUE TITLE
No node v67+ support, due to libxmljs issue

### ISSUE THREAD

**Issue by kitsunekyo** [dotcore64/gulp-xml-transformer#6]
https://github.com/libxmljs/libxmljs/issues/544

as libxmljs seems to be pretty dead, would it be possible to replace it with [libxmljs2](https://github.com/marudor/libxmljs2)?

**Comment by perrin4869** [comment]
Seems like a good idea, all things considered. A PR would be very helpful! Thanks!

**Comment by perrin4869** [comment]
Done in version 4!
